//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABASTECIMENTO
    {
        public int ID { get; set; }
        public System.DateTime DATA_ABASTECIMENTO { get; set; }
        public double KM { get; set; }
        public string POSTO { get; set; }
        public double LITROS_COMBUSTIVEL { get; set; }
        public double DISTANCIA_PERCORRIDA { get; set; }
        public double CONSUMO_MEDIO { get; set; }
        public int FK_VEICULO { get; set; }
        public Nullable<int> FK_TANQUE_COMBUSTIVEL { get; set; }
        public int FK_FUNCIONARIO { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual TANQUE TANQUE { get; set; }
        public virtual VEICULO VEICULO { get; set; }
    }
}
