//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inter
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMBUSTIVEL_DISPONIVEL
    {
        public int ID { get; set; }
        public int FK_TANQUE { get; set; }
        public double QUANTIDADE { get; set; }
    
        public virtual TANQUE TANQUE { get; set; }
    }
}
