//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inter
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORNECEDOR()
        {
            this.PRODUTO_ENTRADA = new HashSet<PRODUTO_ENTRADA>();
        }
    
        public int ID { get; set; }
        public string NOME { get; set; }
        public string CNPJ { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string CONTATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_ENTRADA> PRODUTO_ENTRADA { get; set; }
    }
}
