//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VIACAOARAUJOEntities : DbContext
    {
        public VIACAOARAUJOEntities()
            : base("name=VIACAOARAUJOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABASTECIMENTO> ABASTECIMENTO { get; set; }
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<COMBUSTIVEL_DISPONIVEL> COMBUSTIVEL_DISPONIVEL { get; set; }
        public virtual DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public virtual DbSet<LOGIN> LOGIN { get; set; }
        public virtual DbSet<MANUTENCAO> MANUTENCAO { get; set; }
        public virtual DbSet<QUANTIDADE_TANQUE> QUANTIDADE_TANQUE { get; set; }
        public virtual DbSet<TANQUE> TANQUE { get; set; }
        public virtual DbSet<VEICULO> VEICULO { get; set; }
    }
}
