//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inter
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEICULO()
        {
            this.ABASTECIMENTO = new HashSet<ABASTECIMENTO>();
            this.MANUTENCAO = new HashSet<MANUTENCAO>();
            this.PRODUTO_SAIDA = new HashSet<PRODUTO_SAIDA>();
        }
    
        public int ID { get; set; }
        public string PLACA { get; set; }
        public string PREFIXO { get; set; }
        public double KM_COMPRA { get; set; }
        public double KM_ATUAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABASTECIMENTO> ABASTECIMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANUTENCAO> MANUTENCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_SAIDA> PRODUTO_SAIDA { get; set; }
    }
}
